name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  testing:
    name: Drupal ${{ matrix.drupal-core }} - PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: drupal
          MYSQL_DATABASE: db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: '8.3'
            drupal-core: '10.3.x-dev'
          - php-version: '8.3'
            drupal-core: '11.x-dev'
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Setup Drupal action
        uses: bluehorndigital/setup-drupal@v1.1.0
        with:
          version: ${{ matrix.drupal-core }}
          dependencies: 'drupal/coder:^8.3'
      - name: Checkout module
        uses: actions/checkout@v4
      - name: Copy module into drupal installation
        run: mkdir -p ~/drupal/web/modules/contrib && cp -ar ~/work/psu_form_error_handler ~/drupal/web/modules/contrib
      - name: Check coding standards
        run: ~/drupal/vendor/bin/phpcs --standard=Drupal,DrupalPractice --extensions=php,module,install,js ~/drupal/web/modules/contrib/psu_form_error_handler
      - name: Run php built-in server
        run: php -S 127.0.0.1:8080 -t ~/drupal/web &
      - name: Run functional tests
        run: cd ~/drupal/web && \export SIMPLETEST_BASE_URL="http://127.0.0.1:8080" && export SIMPLETEST_DB="mysql://root:drupal@127.0.0.1:3306/db" && export SYMFONY_DEPRECATIONS_HELPER="999999" &&  ../vendor/bin/phpunit -c core modules/contrib/psu_form_error_handler